### ISSUE TITLE
Variables no usadas

### ISSUE THREAD

**Issue by javatlacati** [gonzalo290378/GestionAeropuertoJava#13]
Hay algunas variables que no se usan como es el caso de `menuBar1`. ¡Que mueran!.

**Comment by gonzalo290378** [comment]
hola! Si, he subido una version preliminar, todas las variables y metodos voy a utilizarlos.
Gracias por todas las recomendaciones que me estas haciendo! Me viene genial!!!!
Un abrazo desde Bs As

**Comment by javatlacati** [comment]
que es Bs As? Supongo que son abreviaturas de ciudad y estado de gringolandia pero no le los sé aún... tal vez debería echarme una canción para memorizarlos

**Comment by gonzalo290378** [comment]
ajja Buenos Aires! Argentina!
