### ISSUE TITLE
Error:(43, 65) java: package org.netbeans.lib.awtextra does not exist.

### ISSUE THREAD

**Issue by javatlacati** [gonzalo290378/GestionAeropuertoJava#3]
Debido a #1 no se incluyen las dependencias en el build.

Para evitar este problema muchas personas remplazaron el absolute layout que era en ese momento propietario por los layouts tradicionales. Desconozco si el absolute layout fue donado a la fundación apache.

**Comment by gonzalo290378** [comment]
Cuando hablas de dependencias, que deberia hacer?

**Comment by javatlacati** [comment]
Buscar en tu ide cada una y decirme que versión tienen. En este caso yo ya sé por el nombre de paquete que se llama `Absolute Layout` y que fue introducida para el desarrollo de interfaces de netbeans allá por la versión 6 aproximadamente, pero al ser una librería propietaria ellos mismos después te la cambiaban.

**Comment by gonzalo290378** [comment]
Bueno, aca hemos averiguado la version. 
Tendria que haber grabado la clase de programacion que me diste ayer!
El mago de Oz :)
