### ISSUE TITLE
Imports totalmente calificados

### ISSUE THREAD

**Issue by javatlacati** [gonzalo290378/GestionAeropuertoJava#4]
Son innecesarios y no estándard.

Puedes configurar matisse para que la generación de código sea con imports en vez de poner los nombres totalmente calificados para los componentes gráficos.

**Comment by gonzalo290378** [comment]
Perdon, aca no entendi!

**Comment by javatlacati** [comment]
jlabel1 = new java.swing.JLabel()

lo común es poner imports para eso

**Comment by gonzalo290378** [comment]
Bien, ya encontre esa linea, la hizo automaticamente netbeans. Como se puede configurar esas cosas en este IDE? Como que genera mucho codigo basura. Que IDE utilizas vos? En eclipse lo veo todo mas limpio, creo

**Comment by javatlacati** [comment]
Igual netbeans, su Matisse es lo mejor que le ha pasado al desarrollo de aplicaciones de escritorio con gráficos en Java.
En tu form lo seleccionas desde el inspector luego en la ventana de propiedades seleccionas el tab código y allí le deseleccionas el checkbox de generar imports totalmente calificados, así de simple

**Comment by gonzalo290378** [comment]
Excelente!! realizado
