### ISSUE TITLE
Las credenciales de acceso están harcodeadas

### ISSUE THREAD

**Issue by javatlacati** [gonzalo290378/GestionAeropuertoJava#6]
Por motivos de seguridad es mejor sacar las credenciales de acceso fuera del código.

**Comment by gonzalo290378** [comment]
Cuales son las credenciales de acceso que subi?

**Comment by javatlacati** [comment]
admin admin

**Comment by gonzalo290378** [comment]
entendido!

**Comment by gonzalo290378** [comment]
Perfecto. Ya lo modifique en mi IDE, para acceder con user: "" - pass:"" con aclaracion incluida.

**Comment by javatlacati** [comment]
No es malo que se requieran credenciales... lo malo es ponerlas en el codigo. Si no quieres acceso con credenciales también está bien.
