### ISSUE TITLE
nombres genéricos de variables

### ISSUE THREAD

**Issue by javatlacati** [gonzalo290378/GestionAeropuertoJava#7]
Nombres de variables como `jLabel1`,` jLabel2`, etc no tienen ningún valor semántico.

El ideal sería ponerles un nombre que indique para qué sirven como por ejemplo se hacía en VBasic `txtNombreUsuario`.

**Comment by gonzalo290378** [comment]
Si! todas las variables van a tener un uso, gracias!

**Comment by javatlacati** [comment]
además del uso es mejor si tienen un buen nombre 😄

**Comment by gonzalo290378** [comment]
Correcto!!! Gracias!
