### ISSUE TITLE
No manejar el flujo confiando en el manejo de excepciones

### ISSUE THREAD

**Issue by javatlacati** [gonzalo290378/GestionAeropuertoJava#9]
Es un mal diseño y un mal uso de la filosof[ia de las excepciones, se debe evitar en la medida de lo posible.

**Comment by gonzalo290378** [comment]
Me han recomendado asserts para ese caso, pero aun no se utilizarlos. Tambien REGEX, que opinas?

**Comment by javatlacati** [comment]
Dependería el caso particular. Pero para entrada que es donde lo ví creo que podrías hallar muchas formas de hacr lo mismo. No dudes en preguntar en soes, a veces hay gente brillante allí

**Comment by gonzalo290378** [comment]
Buen consejo! Gracias, buscare en SOES, es una web?

**Comment by javatlacati** [comment]
StackOverflowESpañol = SOES al menos así le llamamos coloquialmente los usuarios 😄

**Comment by gonzalo290378** [comment]
Lo dejo abierto, ya que necesito optimizar en el nuevo proyecto el uso de excepciones. Creo que los Assert son excelentes y regex tambien.
Bien! apuntado! SOES!
